# Generated by Django 5.1.6 on 2025-05-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
    ]
